os:
    - linux
dist: xenial
language: node_js
node_js:
    - 12
services:
    - postgresql
addons:
    postgresql: "12"
    apt:
        packages:
            - postgresql-12
            - postgresql-client-12
jobs:
    include:
        - node_js: "12.18.4"
before_script:
    - cp config/database.yml.travis config/database.yml
script:
    - yarn test
    - yarn run coveralls
cache:
    bundler: true
    directories:
        - node_modules
    yarn: true
after_success:
    - codecov