os:
    - linux
dist: xenial
language: node_js
node_js:
    - 12
services:
    - postgresql
addons:
    postgresql: "12"
jobs:
    include:
        - node_js: "12.18.4"
script:
    - yarn test
    - yarn run coveralls
cache: yarn
after_success:
    - codecov