os:
    - linux
dist: xenial
language: node_js
node_js:
    - 12
addons:
    postgresql: "12"
    apt:
        packages:
            - postgresql-12
            - postgresql-client-12
            - postgresql-server-dev-12
env:
    PGPORT: "5433"
    PGUSER: "postgres"
jobs:
    include:
        - node_js: "12.18.4"
before_script:
    - sudo systemctl stop postgresql@12-main && sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/12/main/pg_hba.conf && sudo systemctl start postgresql@12-main
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - yarn test
cache:
    bundler: true
    directories:
        - node_modules
    yarn: true
after_success:
    - yarn run coveralls
    - codecov