sudo: false
language: node_js
node_js:
    - 12
services:
    - postgresql
addons:
    postgresql: "12"
matrix:
    include:
        - node_js: "12.18.4"
script:
    - yarn test
    - yarn run coveralls
env:
    global:
        - PGPORT=5433