os:
    - linux
dist: xenial
language: node_js
node_js:
    - 12
addons:
    postgresql: "9.4"
services:
    - postgresql
env:
    PGPORT: "5432"
    PGUSER: "postgres"
jobs:
    include:
        - node_js: "12.18.4"
script:
    - yarn test
cache:
    bundler: true
    directories:
        - node_modules
    yarn: true
after_script:
    - yarn coveralls